<?php

namespace Blogger\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaRepository extends EntityRepository
{

	/**public function getCategoriaForVideo($CategoriaId)
	*{
	*	$qp = $this->createQueryBuilder('c')->select('c')->where('c.id = :categoria_id')-> *setParameter('categoria_id', $CategoriaId);
*
*		return $qp->getQuery()->getResult();}
*/	
public function getAllCategorias($limit = null)
{
	$qp = $this->createQueryBuilder('c')->select('c')->addOrderBy('c.nombre', 'DESC');

	if (false === is_null($limit))
		$qp->setMaxResults($limit);

	return $qp->getQuery()->getResult();
}


}
