<?php

namespace Blogger\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlatafomaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlatafomaRepository extends EntityRepository
{

	public function getLatestPlats($limit = null)
{
	$qp = $this->createQueryBuilder('p')->select('p')->addOrderBy('p.nombre', 'DESC');

	if (false === is_null($limit))
		$qp->setMaxResults($limit);

	return $qp->getQuery()->getResult();
}
	
}
