blogger_blog_homepage:
    path:     /
    defaults: { _controller: BloggerBlogBundle:Default:index }
    
blogger_blog_list:
    path: /blog
    defaults: { _controller: BloggerBlogBundle:Blog:list }

blogger_blog_show:
    path: /blog/show/{id}
    defaults: { _controller: BloggerBlogBundle:Blog:show }

