blogger_blog_list:
    path: /
    defaults: { _controller: BloggerBlogBundle:Blog:list }

blogger_blog_show:
    path: /show/{id}
    defaults: { _controller: BloggerBlogBundle:Blog:show }

blogger_blog_contact:
    path:  /contact
    defaults: { _controller: BloggerBlogBundle:Blog:contact }


blogger_blog_init:
    path:  /init
    defaults: { _controller: BloggerBlogBundle:Blog:inicio }

blogger_blog_show_categoria_ajax:
    path:  /show_cat_ajax/{id}
    defaults: { _controller: BloggerBlogBundle:Blog:show_cat_ajax }

blogger_blog_list_plat:
    path: /plataformas
    defaults: { _controller: BloggerBlogBundle:Blog:list_plat }

blogger_blog_show_categoria:
    path: /show_cat/{id}
    defaults: { _controller: BloggerBlogBundle:Blog:show_cat }

blogger_comment_create:
    path:  /comentario/{video_id}
    defaults: { _controller: BloggerBlogBundle:Comentario:create }
    requirements:
        _method: GET
        post_id: \d+

blogger_like_create:
    path:  /like/{video_id}
    defaults: { _controller: BloggerBlogBundle:MeGusta:create }
    requirements:
        _method: POST|GET
       

blogger_blog_show_ajax:
    path: /show_ajax/{id}
    defaults: { _controller: BloggerBlogBundle:Blog:show_ajax }
  
  




